/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import mapview.MapView;

/**
 *
 * @author Yihao
 */
public class CreateAccountFrame extends javax.swing.JFrame {
    String JDBC_DRIVER= "com.mysql.jdbc.Driver";  
    String DB_URL = "jdbc:mysql://localhost/map509";
    String USER = "root";
    String PASS = "";
    Connection con;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form CreateAccountFrame
     */
    public CreateAccountFrame() {
        connect();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void connect() {
        try {
            String driver = JDBC_DRIVER;
            Class.forName(driver);
            
            con = DriverManager.getConnection(DB_URL,USER,PASS);
            st = con.createStatement();
            
            
        }
        catch(Exception ex) {
        System.out.println("Problem creating connection.");
        }
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        username2 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        rtPassword2 = new javax.swing.JLabel();
        userTextField2 = new javax.swing.JTextField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jPasswordField6 = new javax.swing.JPasswordField();
        createButton2 = new javax.swing.JButton();
        cancelButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create New Account");
        setPreferredSize(new java.awt.Dimension(451, 300));

        jPanel3.setLayout(null);

        username2.setFont(new java.awt.Font("Roboto Bk", 0, 12)); // NOI18N
        username2.setText("Username");
        jPanel3.add(username2);
        username2.setBounds(120, 60, 60, 15);

        password2.setFont(new java.awt.Font("Roboto Bk", 0, 12)); // NOI18N
        password2.setText("Password");
        jPanel3.add(password2);
        password2.setBounds(120, 100, 70, 15);

        rtPassword2.setFont(new java.awt.Font("Roboto Bk", 0, 12)); // NOI18N
        rtPassword2.setText("Re-type Password");
        jPanel3.add(rtPassword2);
        rtPassword2.setBounds(80, 140, 110, 15);

        userTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(userTextField2);
        userTextField2.setBounds(190, 51, 130, 30);
        jPanel3.add(jPasswordField5);
        jPasswordField5.setBounds(190, 91, 130, 30);
        jPanel3.add(jPasswordField6);
        jPasswordField6.setBounds(190, 131, 130, 30);

        createButton2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        createButton2.setText("Create");
        createButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(createButton2);
        createButton2.setBounds(110, 210, 82, 29);

        cancelButton2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cancelButton2.setText("Cancel");
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(cancelButton2);
        cancelButton2.setBounds(250, 210, 82, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(451, 350));
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextField2ActionPerformed

    private void createButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton2ActionPerformed
        try {
            String username = userTextField2.getText().trim();		
            String password = new String(jPasswordField5.getPassword());		
            String passwordCheck = new String(jPasswordField6.getPassword());		
            String sql = "select username from user where username = '"+username+"';";		
            rs = st.executeQuery(sql);		
            int count = 0;		
            while(rs.next()){		
                count++;		
            }		
            if(count > 0) {		
                JOptionPane.showMessageDialog(null, "Same username existed. Please choose another username."); 		
            }		
            else if (username.equals("")){		
                JOptionPane.showMessageDialog(null, "Please choose a username."); 		
            }		
            else if (password.equals("")) {		
                JOptionPane.showMessageDialog(null, "Password cannot be empty.");            		
            }		
            else if (!password.equals(passwordCheck)) {		
                JOptionPane.showMessageDialog(null, "Retype password is wrong."); 		
            }		
            else {		
                sql = "INSERT INTO user (username, password, type) VALUES (\""+username+"\", \""+password+"\", \"user\");";		
                st.executeUpdate(sql);		
                JOptionPane.showMessageDialog(null, "Account creates successfully."); 		
                this.dispose();		
            }		
        }		
        catch(Exception ex) {		
            JOptionPane.showMessageDialog(null, "problem creating an account."); 		
        }
    }//GEN-LAST:event_createButton2ActionPerformed

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed
            this.dispose();
    }//GEN-LAST:event_cancelButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton2;
    private javax.swing.JButton createButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel rtPassword2;
    private javax.swing.JTextField userTextField2;
    private javax.swing.JLabel username2;
    // End of variables declaration//GEN-END:variables
}
