/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import mapview.MapView;

/**
 *
 * @author Yihao
 */
public class UserLoginFrame extends javax.swing.JFrame {
    String JDBC_DRIVER= "com.mysql.jdbc.Driver";  
    String DB_URL = "jdbc:mysql://localhost/map509";
    String USER = "root";
    String PASS = "";
    Connection con;
    Statement st;
    ResultSet rs;
    private Image back = new ImageIcon(this.getClass().getResource("/icons/back.png")).getImage();

    

    /**
     * Creates new form LoginFrame
     */
    public UserLoginFrame() {
        connect();
        initComponents();
        this.setTitle("User Login");
        this.setLocationRelativeTo(null);
        
       
        
        
    }
    public void paintComponent(Graphics page) {
        super.paintComponents(page);
        page.drawImage(back, 0, 0, null);
    }
    
    public void connect() {
        try {
            String driver = JDBC_DRIVER;
            Class.forName(driver);
            
            con = DriverManager.getConnection(DB_URL,USER,PASS);
            st = con.createStatement();
            
            
        }
        catch(Exception ex) {
        System.out.println("Problem creating connection.");
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        CreateAccountButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(back);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 130, 70, 17);

        jLabel3.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 170, 70, 17);

        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userTextField);
        userTextField.setBounds(150, 121, 169, 30);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(150, 161, 169, 30);

        loginButton.setFont(new java.awt.Font("Roboto Bk", 0, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(150, 200, 170, 30);

        adminButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        adminButton.setText("<HTML><FONT color=\"#000099\"><U>Click</U></FONT>"
            + " to login as administrator.</HTML>");
        adminButton.setBorder(null);
        adminButton.setBorderPainted(false);
        adminButton.setContentAreaFilled(false);
        adminButton.setFocusPainted(false);
        adminButton.setHorizontalAlignment(SwingConstants.LEFT);
        adminButton.setBorderPainted(false);
        adminButton.setOpaque(false);
        adminButton.setBackground(Color.WHITE);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton);
        adminButton.setBounds(150, 240, 200, 15);

        CreateAccountButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CreateAccountButton.setText("<HTML><FONT color=\"#000099\"><U>Click</U></FONT>"
            + " to create a new account.</HTML>");
        CreateAccountButton.setBorder(null);

        CreateAccountButton.setBorderPainted(false);

        CreateAccountButton.setContentAreaFilled(false);

        CreateAccountButton.setFocusPainted(false);
        CreateAccountButton.setHorizontalAlignment(SwingConstants.LEFT);
        CreateAccountButton.setBorderPainted(false);
        CreateAccountButton.setOpaque(false);
        CreateAccountButton.setBackground(Color.WHITE);
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateAccountButton);
        CreateAccountButton.setBounds(150, 260, 200, 23);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.jpg"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(140, 10, 230, 100);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(451, 350));
        jPanel1.add(background);
        background.setBounds(0, -20, 450, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        try {
            String username = userTextField.getText().trim();
            String password = new String(jPasswordField1.getPassword());
            String sql = "select username, password from user where username = '"+username+"' and password = '"+password+"';";
            rs = st.executeQuery(sql);
            int count = 0;
            while(rs.next()){
                count++;
            }
            
            if(count == 1){
                MapView mv = new MapView();
                this.dispose();
                
            }
            else if(count > 1) {
                JOptionPane.showMessageDialog(null, "Duplicate users found."); 
            }
            else {
                JOptionPane.showMessageDialog(null, "Username or Password Incorrect!"); 
            }
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Problem login to system."); 
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
        AdminLoginFrame al = new AdminLoginFrame();
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminButtonActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
        // TODO add your handling code here:
        CreateAccountFrame caf = new CreateAccountFrame();
        caf.setVisible(true);
    }//GEN-LAST:event_CreateAccountButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserLoginFrame ul = new UserLoginFrame();
                ul.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
