/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapview;

import java.awt.Color;
import java.awt.Image;
import javax.swing.JPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author GaoYifei
 */
public class RightSideBar extends JPanel implements MouseListener, ActionListener, ListSelectionListener{
    // interface
    public MainPanel mainPanel = null;
    public SecRightSideBar secRightSideBar = null;
    public HigginsPanel higginsPanel = null;
    public MapView mapView = null;
    
    
    
    private JLabel backButton;
    
    /**
     * Creates new form RightSideBar
     * @param mapView
     */
    public RightSideBar() {
        initComponents();
        init();
                
    }
    
    public void init(){
        floorList.addListSelectionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        classroomLabel = new javax.swing.JLabel();
        restroomLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        goCampusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        floorList = new javax.swing.JList();

        setPreferredSize(new java.awt.Dimension(150, 800));

        clearButton.setText("Clear Pins");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        showButton.setText("Show Pins");
        showButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showButtonMouseClicked(evt);
            }
        });

        classroomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/classrooml.png"))); // NOI18N
        classroomLabel.setBounds(new java.awt.Rectangle(100, 200, 45, 16));
        classroomLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classroomLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                classroomLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                classroomLabelMouseEntered(evt);
            }
        });

        restroomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/restrooml.png"))); // NOI18N
        restroomLabel.setBounds(new java.awt.Rectangle(200, 300, 45, 16));
        restroomLabel.setPreferredSize(new java.awt.Dimension(150, 800));
        restroomLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restroomLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restroomLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restroomLabelMouseEntered(evt);
            }
        });

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Left Arrow.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        goCampusButton.setText("Campus Map");
        goCampusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goCampusButtonMouseClicked(evt);
            }
        });

        floorList.setBorder(javax.swing.BorderFactory.createTitledBorder("Floor "));
        floorList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Project Center 1st  Floor", "Project Center 2ed Floor", "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        floorList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        floorList.setToolTipText("Choose Floor in Project Center");
        jScrollPane1.setViewportView(floorList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restroomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classroomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(goCampusButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(clearButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(classroomLabel)
                .addGap(85, 85, 85)
                .addComponent(restroomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goCampusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showButton)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.clearPins();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void classroomLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classroomLabelMouseClicked
        // TODO add your handling code here:
       //System.out.println("classroom clicked");
        secRightSideBar.setVisible(true);
        // change the color of Second Right side bar 
        secRightSideBar.setBackground(new java.awt.Color(231,0,102)); // 1 for red
        // show pins of selected locations in the map 
       // mainPanel.repaint();
        mainPanel.showLocationPin("CLASSROOM");
        // show list of location name in second right side bar
        try {
            secRightSideBar.ShowLocationName("CLASSROOM");
            secRightSideBar.timer.start();
        } catch (SQLException ex) {
            Logger.getLogger(RightSideBar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
    }//GEN-LAST:event_classroomLabelMouseClicked

    private void restroomLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restroomLabelMouseClicked
        // TODO add your handling code here:
       // System.out.println("restroom clicked");
        secRightSideBar.setVisible(true);
       
        secRightSideBar.setBackground(new java.awt.Color(38,195,194)); // 2 for yellow
        
        //mainPanel.repaint();
        mainPanel.showLocationPin("RESTROOM");
        
        try {
            
            secRightSideBar.ShowLocationName("RESTROOM");
            secRightSideBar.timer.start();
        } catch (SQLException ex) {
            Logger.getLogger(RightSideBar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_restroomLabelMouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
//        secRightSideBar.setBackground(Color.white);
        secRightSideBar.setVisible(false);
    }//GEN-LAST:event_backLabelMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_clearButtonMouseClicked

    private void classroomLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classroomLabelMouseEntered
        // TODO add your handling code here:
        
        this.classroomLabel.setBounds(this.classroomLabel.getX() - 5, this.classroomLabel.getY() - 10,
           this.classroomLabel.getHeight() , this.classroomLabel.getWidth() );
        this.classroomLabel.setToolTipText("Classrooms");
        this.repaint();
    }//GEN-LAST:event_classroomLabelMouseEntered

    private void classroomLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classroomLabelMouseExited
        // TODO add your handling code here:
         this.classroomLabel.setBounds(this.classroomLabel.getX() + 5, this.classroomLabel.getY() + 10,
           this.classroomLabel.getHeight() , this.classroomLabel.getWidth() );
        this.repaint();
    }//GEN-LAST:event_classroomLabelMouseExited

    private void restroomLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restroomLabelMouseEntered
        // TODO add your handling code here:
        this.restroomLabel.setBounds(this.restroomLabel.getX() - 5, this.restroomLabel.getY() - 5,
           this.restroomLabel.getHeight() , this.restroomLabel.getWidth() );
        this.restroomLabel.setToolTipText("Restrooms");
        this.repaint();
    }//GEN-LAST:event_restroomLabelMouseEntered

    private void restroomLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restroomLabelMouseExited
        // TODO add your handling code here:
        this.restroomLabel.setBounds(this.restroomLabel.getX() + 5, this.restroomLabel.getY() + 5,
           this.restroomLabel.getHeight() , this.restroomLabel.getWidth() );
        this.repaint();
    }//GEN-LAST:event_restroomLabelMouseExited

    private void showButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showButtonMouseClicked
        // TODO add your handling code here:
        mainPanel.showPins();
    }//GEN-LAST:event_showButtonMouseClicked

    private void goCampusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goCampusButtonMouseClicked
        try {
            // TODO add your handling code here:
            mapView.init(higginsPanel);
            
        } catch (SQLException ex) {
            Logger.getLogger(RightSideBar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_goCampusButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel classroomLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JList floorList;
    private javax.swing.JButton goCampusButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel restroomLabel;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void actionPerformed(ActionEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if( e.getSource() == floorList && ! e.getValueIsAdjusting())
		{
			// Get the current selection and place it in the
			// edit field
			String stringValue = (String)floorList.getSelectedValue();
			//System.out.println("list"+stringValue);
                        int mapIndex;
                        if(stringValue.equals("Project Center 1st  Floor")){
                            System.out.print("1st ");
                            try {
                                mapIndex = 1;
                                mainPanel.init(mapIndex);
                                mainPanel.repaint();
                            } catch (SQLException ex) {
                                Logger.getLogger(RightSideBar.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        if(stringValue.equals("Project Center 2ed Floor")){
                             System.out.print("2nd ");
                            try {
                                mapIndex = 2;
                                mainPanel.init(mapIndex);
                                mainPanel.repaint();
                            } catch (SQLException ex) {
                                Logger.getLogger(RightSideBar.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
				
		}
        
    }
}
