/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapview;
import adminmodule.Location;
import adminmodule.MapInfo;
import java.awt.BorderLayout;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JLabel;
import jdbc.JDBC;
import javax.swing.WindowConstants;
import static javax.swing.text.StyleConstants.Bold;

/**
 *
 * @author GaoYifei
 */
public class SecRightSideBar extends javax.swing.JPanel implements MouseListener,ActionListener {
    
 
    /**
     * Creates new form SecRightSideBar
     */
    public SecRightSideBar() {

        initComponents();
    }
   
   
        
 
    public void ShowLocationName(String category) throws SQLException{
        this.removeAll();
        ArrayList<Location> locationList = new ArrayList<Location>();
        ArrayList<JLabel> labelList = new ArrayList<JLabel>();
       
        JDBC db = new JDBC();
        //System.out.println(Category);     
        MapInfo info = db.getMapInfo(1);
        locationList = info.locations;
        
        
        
        
        for(Location l: locationList){
            
             switch(l.category)
                    {
                        case DINING:
                            if(category.equals("DINING")){
                            JLabel label = new JLabel();
                            label.setText(l.name);
                           
                            labelList.add(label);
                            
                              
                            
                            }
                            break;
                        case PARKING:
                           
                            if(category.equals("PARKING")){
                            JLabel label = new JLabel();
                            label.setText(l.name);
                            
                            labelList.add(label);
                            
                              
                            }
                       
                            
                           
                        default:
                            break;
//                
                     }
           
        }
        int y = 0;
        for(JLabel j: labelList){
           
            Font font = new Font("Roboto", Font.BOLD, 16);
            j.setFont(font);
            j.setBounds(60, 90 + y, 160, 30);
            j.setForeground(Color.white);
            this.add(j);
            
            y = y + 30;
       
        }
       
//        JLabel label = new JLabel();
//        Font font = new Font("Roboto", Font.BOLD, 16);
//        label.setFont(font);
//        label.setBounds(60, 60, 160, 30);
//        label.setForeground(Color.white);
        //label.setFont(Font.BOLD);
        //label.setText("Just Testing");
        
        //this.add(label);
        BorderLayout layout;
        layout = new BorderLayout();
        this.setLayout(layout);
        
        
        this.validate();
        this.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
//    @Override
//    public void paintComponent(Graphics g){
//        super.paintComponent(g);
//        this.setBackground(Color.red);
//    }
    @Override
    public void mouseClicked(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
